name: heimdall
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - libcxx=21.1.8
  - libexpat=2.7.4
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.19
  - packaging=25.0
  - pip=26.0.1
  - python=3.11.14
  - readline=8.3
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - numpy==2.4.2
      - pandas==3.0.0
      - psycopg2-binary==2.9.11
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - rich==14.3.2
      - six==1.17.0
      - sqlalchemy==2.0.46
      - typing-extensions==4.15.0
prefix: /opt/anaconda3/envs/heimdall
